config/routes.rb
  MoodyOn::Application.routes.draw do

    scope "static_pages" do
      get '/about' => 'static_pages#about'
      get '/blog'  => 'static_pages#blog'
      get '/developers' => 'static_pages#developers'
      get '/jobs'  => 'static_pages#jobs'
      get '/privacy' => 'static_pages#privacy'
      get '/terms'   => 'static_pages#terms'
      get '/contact' => 'static_pages#contact'
      get '/help'	 => 'static_pages#help'
    end

      
      resources :events
      resources :reasons
      resources :moods 
      resources :sub_moods

    match '/moods_for_selection' => 'home#moods_for_selection'
    match '/edit_profile' => 'home#edit_profile'
    match '/profile' => 'home#profile'
    match '/home/update_state_select/:id' => 'home#update_state_select'
    match '/home/update_city_select/:id' => 'home#update_city_select'
    match '/enter_sub_mood' => 'home#enter_sub_mood'
    match '/home/city_for_graph/:id' => 'home#city_for_graph' 
      

    
    
    
    devise_for :users,
      :controllers => { 
	      :sessions           => 'devise/sessions', 
	      :registrations      => 'devise/registrations', 
	      :confirmations      => 'devise/confirmations', 
        :passwords          => 'devise/passwords',
        :omniauth_callbacks => 'users/omniauth_callbacks'
      }, :path => '', :path_names => {
                        :sign_in => 'users/sign_in', 
                        :sign_out => 'users/sign_out', 
                        :sign_up => 'users/sign_up'
                      }
    resources :users
    
    
    
    root :to => "home#index"
  end

app/models/reason.rb
class Reason < ActiveRecord::Base
  attr_accessible :name
  has_many :user_sub_moods
  
  validates :name, :presence => true
end

app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
    before_filter :authenticate_user!
    before_filter :is_admin?, :except =>  [:index]
  # GET /reasons
  # GET /reasons.json
  def index
    @reasons = Reason.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reasons }
    end
  end

  # GET /reasons/1
  # GET /reasons/1.json
  def show
    @reason = Reason.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reason }
    end
  end

  # GET /reasons/new
  # GET /reasons/new.json
  def new
    @reason = Reason.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reason }
    end
  end

  # GET /reasons/1/edit
  def edit
    @reason = Reason.find(params[:id])
  end

  # POST /reasons
  # POST /reasons.json
  def create
    @reason = Reason.new(params[:reason])

    respond_to do |format|
      if @reason.save
        format.html { redirect_to @reason, notice: 'Reason was successfully created.' }
        format.json { render json: @reason, status: :created, location: @reason }
      else
        format.html { render action: "new" }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reasons/1
  # PUT /reasons/1.json
  def update
    @reason = Reason.find(params[:id])

    respond_to do |format|
      if @reason.update_attributes(params[:reason])
        format.html { redirect_to @reason, notice: 'Reason was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reasons/1
  # DELETE /reasons/1.json
  def destroy
    @reason = Reason.find(params[:id])
    @reason.destroy

    respond_to do |format|
      format.html { redirect_to reasons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/views/reasons/_form.html.erb
<%= simple_form_for(@reason) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reasons/edit.html.erb
<h1>Editing reason</h1>

<%= render 'form' %>

<%= link_to 'Show', @reason %> |
<%= link_to 'Back', reasons_path %>

app/views/reasons/index.html.erb
<h1>Listing reasons</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reasons.each do |reason| %>
  <tr>
    <td><%= reason.name %></td>
    <td><%= link_to 'Show', reason %></td>
    <td><%= link_to 'Edit', edit_reason_path(reason) %></td>
    <td><%= link_to 'Destroy', reason, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reason', new_reason_path, if current_user.has_role? :admin %>

app/views/reasons/new.html.erb
<h1>New reason</h1>

<%= render 'form' %>

<%= link_to 'Back', reasons_path %>

app/views/reasons/show.html.erb
<p>
  <b>Name:</b>
  <%= @reason.name %>
</p>


<%= link_to 'Edit', edit_reason_path(@reason) %> |
<%= link_to 'Back', reasons_path %>