config/routes.rb
  MoodyOn::Application.routes.draw do

    scope "static_pages" do
      get '/about' => 'static_pages#about'
      get '/blog'  => 'static_pages#blog'
      get '/developers' => 'static_pages#developers'
      get '/jobs'  => 'static_pages#jobs'
      get '/privacy' => 'static_pages#privacy'
      get '/terms'   => 'static_pages#terms'
      get '/contact' => 'static_pages#contact'
      get '/help'	 => 'static_pages#help'
    end

      
      resources :events
      resources :reasons
      resources :moods 
      resources :sub_moods

    match '/moods_for_selection' => 'home#moods_for_selection'
    match '/edit_profile' => 'home#edit_profile'
    match '/profile' => 'home#profile'
    match '/home/update_state_select/:id' => 'home#update_state_select'
    match '/home/update_city_select/:id' => 'home#update_city_select'
    match '/enter_sub_mood' => 'home#enter_sub_mood'
    match '/home/city_for_graph/:id' => 'home#city_for_graph' 
      

    
    
    
    devise_for :users,
      :controllers => { 
	      :sessions           => 'devise/sessions', 
	      :registrations      => 'devise/registrations', 
	      :confirmations      => 'devise/confirmations', 
        :passwords          => 'devise/passwords',
        :omniauth_callbacks => 'users/omniauth_callbacks'
      }, :path => '', :path_names => {
                        :sign_in => 'users/sign_in', 
                        :sign_out => 'users/sign_out', 
                        :sign_up => 'users/sign_up'
                      }
    resources :users
    
    
    
    root :to => "home#index"
  end

app/controllers/home_controller.rb
  class HomeController < ApplicationController
      before_filter :authenticate_user!
      before_filter :is_admin?, :except =>  [:index, :moods_for_selection,:show_sub_moods, :profile, :edit_profile, :city_for_graph, :update_state_select, :update_city_select, :enter_sub_mood]
    
    def index
    @users = User.all
    @profiles = Profile.all
    #@city = City.all
    @moods = Mood.order 'name'
    @sub_moods = SubMood.dep_sub_mood(params[:id])
      
    end

  def city_for_graph
    #debugger
    users = current_user.mood_according_city(params[:id])
    moods = users.collect.each {|user| user.sub_mood.mood.name}
    render :partial => "home/city_for_graph", :locals => {:users => users, :moods => moods }
  end
    
    def moods_for_selection
      @moods = Mood.ordered_mood
      respond_to do |format|
	     format.js
      end
    end
      
    def update_state_select  
      states = State.where(:country_id=>params[:id]).order(:name) unless params[:id].blank?
      render :partial => "states", :locals => { :states => states } 
    end 
    
    def update_city_select
      cities = City.where(:state_id=>params[:id]).order(:name) unless params[:id].blank?
      render :partial => "cities", :locals => { :cities => cities }
    end

    def edit_profile
      @profile = current_user.profile
      @gender = ["Male", "Female"]
      @marital_status = ["Single", "Married", "Engaged", "Complicated", 
                         "Open Relationship",	"Widowed", "Seperated", "Dicorced"]
    end

    def profile
      @profile = current_user.profile
  
      if current_user.profile.present?
      	if current_user.profile.update_attributes(params[:profile])
      	  flash[:notice] = "Profile saved successfully."
      	  #redirect_to "/show_profile/#{current_user.id}"
      	  redirect_to "/"
      	else
      	  flash[:error] = "Something went wrong."
      	  redirect_to :back
      	end
      end
    end
    
    def enter_sub_mood
      @user_sub_mood = current_user.user_sub_moods.new(params[:user_sub_mood])
      respond_to do |format|
    	if params[:user_sub_mood].present?
    	  if @user_sub_mood.save
    	    
    	    format.html { redirect_to "/", notice: "Your are in #{@user_sub_mood.sub_mood.name} mood now." }
    	    format.json { render json: "/", status: :created, location: @sub_mood }
    	  else
    	    format.html { render action: "new" }
    	    format.json { render json: @user_sub_mood.errors, status: :unprocessable_entity }
    	  end
    	end
      end
    end    
    
    
      
  end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_cities.html.erb
<%= simple_form_for :profile do |f| %>
  <div class="control-group">
    <label class="control-label" for="inputCity">City</label>
      <div class="controls"> 
	<% if !cities.blank? %>
	<%#= debug f.input_field :city_id, :collection=>cities.collect{ |c| [c.name,c.id]} %>
	  <%= f.input_field :city_id, :collection=>cities.collect{ |c| [c.name,c.id]} %>
	<% else %>
	  <%= f.input_field :city_id, :collection=>[] %>
	<% end %>
      </div>
   </div>
<% end %> 

app/views/home/_city_for_graph.html.erb
<script>
$(document).ready(function(){
	var chart;
	var city1 = $('select#city1_select :selected').val();
        var city2 = $('select#city2_select :selected').val();
    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'container',
                type: 'line',
                marginRight: 130,
                marginBottom: 25
            },
            title: {
                text: 'Average Moods of ' + city1 + ' and ' + city2,
                x: -20 //center
            },
            subtitle: {
                text: 'Source: MoodyOn.com',
                x: -20
            },
            xAxis: {
                categories: [<% moods.uniq.each do |mood| %>
				'<%= mood %>', <%#= moods.last ? "," : "" %>
				<% end %>
				
			    ]
            },
            yAxis: {
                title: {
                    text: 'Users count in number'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                formatter: function() {
                        return '<b>'+ this.series.name +'</b><br/>'+
                        this.x +': '+ this.y;
                }
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'top',
                x: -10,
                y: 100,
                borderWidth: 0
            },
            series: [{
                name: city1,
                data: [<%= users.sort.count{|x| x.sub_mood.mood.name == 'Glad'} %>, <%= users.sort.count{|x| x.sub_mood.mood.name == 'Mad'} %>, <%= users.sort.count{|x| x.sub_mood.mood.name == 'Normal'} %>, <%= users.sort.count{|x| x.sub_mood.mood.name == 'Sad'} %> ]
            }, {
                name: city2,
                data: [<%= users.sort.count{|x| x.sub_mood.mood.name == 'Glad'} %>, <%= users.sort.count{|x| x.sub_mood.mood.name == 'Mad'} %>, <%= users.sort.count{|x| x.sub_mood.mood.name == 'Normal'} %>, <%= users.sort.count{|x| x.sub_mood.mood.name == 'Sad'} %>]
            }]
        });
    });
    
});
</script>

app/views/home/_moods_for_selection.html.erb
<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Glad</a></li>
    <li><a href="#tab2" data-toggle="tab">Mad</a></li>
    <li><a href="#tab3" data-toggle="tab">Normal</a></li>
    <li><a href="#tab4" data-toggle="tab">Sad</a></li>
  </ul>
  <h3>
    <%= "What is your mood today?" if current_user.has_role? :user %>
    <%= "Listing Moods" if current_user.has_role? :admin %>  
  </h3>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <% @moods[0].sub_moods.each do |mood| %>
	 <%= render :partial => "sub_mood_select", :locals => {:mood => mood} %> 
      <% end %>
    </div>
    <div class="tab-pane" id="tab2">
      <% @moods[1].sub_moods.each do |mood| %>
	 <%= link_to image_tag(mood.sub_mood_picture, title: mood.name) %> 
      <% end %>
    </div>
     <div class="tab-pane" id="tab3">
      <% @moods[2].sub_moods.each do |mood| %>
	 <%= link_to image_tag(mood.sub_mood_picture, title: mood.name) %> 
      <% end %>
    </div>
    <div class="tab-pane" id="tab4">
     <% @moods[3].sub_moods.each do |mood| %>
      <%= link_to image_tag(mood.sub_mood_picture, title: mood.name) %> 
     <% end %>
    </div>
  </div>
  <% if current_user.has_role? :admin %>
    <%= link_to 'New Mood', new_mood_path, :class => "btn btn-primary"   %>
  <% end %>
    <%#= link_to "Click here to Complete Your Profile", new_profile_path if check_profile(current_user) %>
    <%#= link_to "View Your Profile", new_profile_path if !check_profile(current_user) %>
<%#= debug !check_profile(current_user) %>
<%#= debug check_profile(current_user) %>
</div>

app/views/home/_profile_form.html.erb
<!-- <%= label_tag :name %> -->

  <span class="label label-info">Edit your profile information</span>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Upload Picture</label>
      <div class="controls">
	<%= f.input_field :profile_picture %>
    </div>
  </div>
   
  <div class="control-group">
    <label class="control-label" for="inputFirstName">First Name</label>
    <div class="controls">      
      <%= f.input_field :fname, :placeholder => "First Name", :input_html => { :class => 'input-large' } %>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputLastName">Last Name</label>
    <div class="controls">      
      <%= f.input_field :lname, :placeholder => "Last Name", :input_html => { :class => 'input-large' } %>
    </div>
  </div> 
  
  <div class="control-group">
    <label class="control-label" for="inputAddressLine1">Address Line 1</label>
    <div class="controls">      
      <%= f.text_area :address_line_1, :rows => 3, :input_html => { :class => 'input-large' } %>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputAddressLine2">Address Line 2</label>
    <div class="controls">      
      <%= f.text_area :address_line_2, :rows => 3, :input_html => { :class => 'input-large' } %>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputGender">Gender</label>
    <div class="controls"> 
      <%= f.input_field :gender, :as => :select, :collection => @gender.map { |a| [ a ] } %>
    </div>
  </div> 
  
  <div class="control-group">
    <label class="control-label" for="inputDateOfBirth">Date of Birth</label>
    <div class="controls"> 
      <%= f.text_field :date_of_birth, :value=>current_user.profile.date_of_birth.present? ? current_user.profile.date_of_birth : Date.today.strftime('%Y-%m-%d'), :id =>"dp5" %>
    </div>
  </div> 

  <div class="control-group">
    <label class="control-label" for="inputGender">Relationship Status</label>
    <div class="controls"> 
      <%= f.input_field :marital_status, :as => :select, :collection => @marital_status.map { |a| [ a ] } %>
    </div>
  </div> 
 
   <div class="control-group">
    <label class="control-label" for="inputCountry">Country</label>
    <div class="controls"> 
      <%= f.input_field :country_id, :collection=> Country.find(:all, :order=>:name).collect{ |c| [c.name,c.id]} %>
    </div>
   </div>
    
    <div id="addressStates">
      <%= render :partial => 'states' %>
    </div>
    
    <div id="addressCities">
      <%= render :partial => 'cities' %>
    </div>

  <div class="control-group">
    <label class="control-label" for="inputPincode">Pincode</label>
    <div class="controls">      
      <%= f.input_field :pincode, :placeholder => "Pincode", :input_html => { :class => 'input-large' } %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputMobileNo">Mobile</label>
    <div class="controls">      
      <%= f.input_field :mobile_no, :placeholder => "Phone Number", :input_html => { :class => 'input-large' } %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputOrgName">Organisation</label>
    <div class="controls">      
      <%= f.input_field :org_name, :placeholder => "Organisation", :input_html => { :class => 'input-large' } %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputdesignation">Designation</label>
    <div class="controls">      
      <%= f.input_field :designation, :placeholder => "Designation", :input_html => { :class => 'input-large' } %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputdesignation">Profession</label>
    <div class="controls">      
      <%= f.input_field :profession, :placeholder => "Profession", :input_html => { :class => 'input-large' } %>
    </div>
  </div>
  

  
<script>

jQuery(function($) {

  // when the #country field changes
  $("#profile_country_id").change(function() {
    // make a POST call and replace the content
    var country = $('select#profile_country_id :selected').val();
    if(country == "") country="0";
    jQuery.get('/home/update_state_select/'+country, function(data){
        $("#addressStates").html(data);
    })
    return false;
  });

})

</script>
  

app/views/home/_show_profile_menu.html.erb
<li class="active">
  <a href="#tab1" data-toggle="tab">Edit Profile</a>
</li>
<li>
  <a href="#tab2" data-toggle="tab">Change Password</a>
</li>
<li>
  <a href="#tab3" data-toggle="tab">Sharing With Other Networks</a>
</li>
<li>
  <a href="#tab4" data-toggle="tab">Privacy Settings</a>
</li>
<li>
  <a href="#tab5" data-toggle="tab">Notifications</a>
</li>
<li>
  <a href="#tab6" data-toggle="tab">Connected Apps</a>
</li>
<li>
  <a href="#tab7" data-toggle="tab">Local Updates</a>
</li>

app/views/home/_states.html.erb
<%= simple_form_for :profile, :method => :get do |f| %>
  <div class="control-group">
    <label class="control-label" for="inputState">State</label>
    <div class="controls"> 
      <% if !states.blank? %>
      	<%= f.input_field :state_id, :collection=>states.collect{ |s| [s.name,s.id]} %>
      <% else %>
	<%= f.input_field :state_id, :collection=>[] %>
      <% end %>
    </div>
   </div>
<% end %>   
      
    
    
<script type="text/javascript">
jQuery(function($) {
// when the #region_id field changes
  $("#profile_state_id").change(function() {
    // make a POST call and replace the content
    var state = $('select#profile_state_id :selected').val();
    if(state == "") state="0";
    jQuery.get('/home/update_city_select/'+state, function(data){
        $("#addressCities").html(data);
    })
    return false;
  });
})
</script>

app/views/home/_sub_mood_select.html.erb
<% if user_signed_in? %>
  <a type="text" style="width:100%;" href="#<%= mood.name %>" data-toggle="modal"><%= image_tag(mood.sub_mood_picture, title: mood.name) %></a>
  <div class="modal fade" id="<%= mood.name %>">
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&times;</a>
      <h3>You are now in <%= mood.name %> mood</h3>
      <p><%= image_tag(mood.sub_mood_picture, title: mood.name) %></p>
    </div>
    <%= simple_form_for :user_sub_mood, :url => {:action => "enter_sub_mood", :controller => "home"}, :html => {class:"form-horizontal", :multipart => true} do |f| %>
    <div class="modal-body">
      <div class="control-group">
	<label class="control-label" for="inputReason">Select a reason</label>
	<div class="controls"> 	
	  <%= f.input_field :reason_id, :collection=> Reason.find(:all, :order=>:name).collect{ |c| [c.name,c.id]}, :input_html => { :class => 'input-large' } %>
	</div>
      </div> 
      <div class="control-group">
	<label class="control-label" for="inputReason">Select a event</label>
	<div class="controls">	
	  <%= f.input_field :event_id, :collection=> Event.find(:all, :order=>:name).collect{ |c| [c.name,c.id]}, :input_html => { :class => 'input-large' } %>
	</div>
      </div>
      <%= f.hidden_field :sub_mood_id, :value => mood.id %>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      <%= f.submit "Submit", :class => "btn btn-primary" %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/home/edit_profile.html.erb
<% if current_user.present? %>
  <div class="tabbable tabs-right">
    <ul class="nav nav-tabs">
      <%= render :partial => "home/show_profile_menu" %>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="tab1">
	<% if @profile.present? %>
	  <%= simple_form_for(@profile, :url => {:action => "profile", :controller => "home"}, :html => {:class=>"form-horizontal", :multipart => true}) do |f| %>
	    <fieldset>
	      <%= render :partial => "home/profile_form", :locals => {:f => f} %>
	      <div class="control-group">
		<div class="controls">
		  <%= f.button :submit, "Save Profile", {:class => "btn btn-large btn-primary"} %>
		</div>
	      </div>
	    </fieldset>
	  <% end %>
	<% end %>
      </div>
      <div class="tab-pane" id="tab2">
	<p>Howdy, I'm in Section 2.</p>
      </div>
      <div class="tab-pane" id="tab3">
	<p>Howdy, I'm in Section 3.</p>
      </div>
    </div>
  </div>
<% end %>


<script>
$(function(){
    $('#dp5').datepicker({ format: 'yyyy-mm-dd'  }); 
})
</script>

app/views/home/enter_sub_mood.html.erb
<span class="span12">
  <h3>Your in <%= @user_sub_mood %> Mood</h3> 
  
  
  
  <%= link_to "Select Mood", moods_for_selection_path, remote:true, class:"btn btn-primary" %>
</span>

app/views/home/index.html.erb
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>


<span class="span12">
  <%= link_to "Select Mood", moods_for_selection_path, remote:true, class:"btn btn-primary" %>
</span>


<div id="container" style="min-width: 400px; height: 400px; margin: 0 auto"></div>




<select name="profile[city1]" id="city1_select">
  <option value="">Select City</option>
  <option value="0">Wardha</option>
  <option value="3988">Nagpur</option>
  <option value="3999">Pune</option>
  <option value="3987">Mumbai</option>
  <option value="Akola">Akola</option>
  <option value="Amravati">Amravati</option>
</select> And

<select name="profile[city2]" id="city2_select">
  <option value="">Select City</option>
  <option value="Wardha">Wardha</option>
  <option value="Nagpur">Nagpur</option>
  <option value="Pune">Pune</option>
  <option value="Mumbai">Mumbai</option>
  <option value="Akola">Akola</option>
  <option value="Amravati">Amravati</option>
</select>



<script>
  $(function($) {
    $("#city1_select").change(function() {
      var city1 = $('select#city1_select :selected').val();
      if(city1 == "") city1 = "select city";
      $.ajax({url: '/home/city_for_graph/'+ city1,
        data: "Success",
        success: function(data){
          $("#container").html(data);
        }
      })
      // jQuery.get('/home/city_for_graph/'+ city, function(data){
      // $("#chart_div").html(data);
      // })
    });
  });
</script>

app/views/home/moods_for_selection.js.erb
$(".span12").html("<%= escape_javascript(render(:partial => "moods_for_selection")) %>");