config/routes.rb
  MoodyOn::Application.routes.draw do

    scope "static_pages" do
      get '/about' => 'static_pages#about'
      get '/blog'  => 'static_pages#blog'
      get '/developers' => 'static_pages#developers'
      get '/jobs'  => 'static_pages#jobs'
      get '/privacy' => 'static_pages#privacy'
      get '/terms'   => 'static_pages#terms'
      get '/contact' => 'static_pages#contact'
      get '/help'	 => 'static_pages#help'
    end

      
      resources :events
      resources :reasons
      resources :moods 
      resources :sub_moods

    match '/moods_for_selection' => 'home#moods_for_selection'
    match '/edit_profile' => 'home#edit_profile'
    match '/profile' => 'home#profile'
    match '/home/update_state_select/:id' => 'home#update_state_select'
    match '/home/update_city_select/:id' => 'home#update_city_select'
    match '/enter_sub_mood' => 'home#enter_sub_mood'
    match '/home/city_for_graph/:id' => 'home#city_for_graph' 
      

    
    
    
    devise_for :users,
      :controllers => { 
	      :sessions           => 'devise/sessions', 
	      :registrations      => 'devise/registrations', 
	      :confirmations      => 'devise/confirmations', 
        :passwords          => 'devise/passwords',
        :omniauth_callbacks => 'users/omniauth_callbacks'
      }, :path => '', :path_names => {
                        :sign_in => 'users/sign_in', 
                        :sign_out => 'users/sign_out', 
                        :sign_up => 'users/sign_up'
                      }
    resources :users
    
    
    
    root :to => "home#index"
  end

app/models/sub_mood.rb
class SubMood < ActiveRecord::Base

  
  attr_accessible :description, :name, :sub_mood_picture, :mood_id
  
  belongs_to :mood
  has_many :user_sub_moods
  
  mount_uploader :sub_mood_picture, MoodPictureUploader
  
  validates :mood_id, :presence => true
  validates :name, :presence => true, :uniqueness => true
  validates_format_of :sub_mood_picture, :with => %r{\.(png|jpg|jpeg|bmp)$}i, :message => "file format doesn't match"
  


  def self.dep_sub_mood(mood)
    sub_mood = SubMood.where(:mood_id => mood)
  end
  
end

app/controllers/sub_moods_controller.rb
class SubMoodsController < ApplicationController
    before_filter :authenticate_user!
    before_filter :is_admin?, :except =>  [:index]
  
  # GET /sub_moods
  # GET /sub_moods.json
  def index
    @sub_moods = SubMood.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sub_moods }
    end
  end

  # GET /sub_moods/1
  # GET /sub_moods/1.json
  def show
    @sub_mood = SubMood.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sub_mood }
    end
  end

  # GET /sub_moods/new
  # GET /sub_moods/new.json
  def new
    @sub_mood = SubMood.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sub_mood }
    end
  end

  # GET /sub_moods/1/edit
  def edit
    @sub_mood = SubMood.find(params[:id])
  end

  # POST /sub_moods
  # POST /sub_moods.json
  def create
    @sub_mood = SubMood.new(params[:sub_mood])

    respond_to do |format|
      if @sub_mood.save
        format.html { redirect_to @sub_mood, notice: 'Sub mood was successfully created.' }
        format.json { render json: @sub_mood, status: :created, location: @sub_mood }
      else
        format.html { render action: "new" }
        format.json { render json: @sub_mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sub_moods/1
  # PUT /sub_moods/1.json
  def update
    @sub_mood = SubMood.find(params[:id])

    respond_to do |format|
      if @sub_mood.update_attributes(params[:sub_mood])
        format.html { redirect_to @sub_mood, notice: 'Sub mood was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sub_mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_moods/1
  # DELETE /sub_moods/1.json
  def destroy
    @sub_mood = SubMood.find(params[:id])
    @sub_mood.destroy

    respond_to do |format|
      format.html { redirect_to sub_moods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sub_moods_helper.rb
module SubMoodsHelper
end

app/views/sub_moods/_form.html.erb
<%= simple_form_for(@sub_mood) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :mood %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :sub_mood_picture, :label => 'upload_picture', :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sub_moods/edit.html.erb
<h1>Editing sub_mood</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub_mood %> |
<%= link_to 'Back', sub_moods_path %>

app/views/sub_moods/index.html.erb
<h1>Listing Sub-moods</h1>

<table>
  <tr>
    <th>Mood</th>
    <th>Name</th>
    <th>Description</th>
    <th>Sub mood picture</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sub_moods.each do |sub_mood| %>
  <tr>
    <td><%= sub_mood.mood.name %></td>
    <td><%= sub_mood.name %></td>
    <td><%= sub_mood.description %></td>
    <td><%= image_tag sub_mood.sub_mood_picture %></td>
    <% if current_user.has_role? :admin %>
    <td><%= link_to 'Show', sub_mood, class: "btn btn-mini" %></td>
    <td><%= link_to 'Edit', edit_sub_mood_path(sub_mood), class: "btn btn-mini" %></td>
    <td><%= link_to 'Destroy', sub_mood, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini" %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sub mood', new_sub_mood_path if current_user.has_role? :admin %>

app/views/sub_moods/new.html.erb
<h1>New sub_mood</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_moods_path %>

app/views/sub_moods/show.html.erb
<p>
  <b>Mood:</b>
  <%= @sub_mood.mood.name %>
</p>

<p>
  <b>Name:</b>
  <%= @sub_mood.name %>
</p>

<p>
  <b>Description:</b>
  <%= @sub_mood.description %>
</p>

<p>
  <b>Sub mood picture:</b>
  <%= image_tag @sub_mood.sub_mood_picture %>
</p>


<%= link_to 'Edit', edit_sub_mood_path(@sub_mood) %> |
<%= link_to 'Back', sub_moods_path %>