config/routes.rb
  MoodyOn::Application.routes.draw do

    scope "static_pages" do
      get '/about' => 'static_pages#about'
      get '/blog'  => 'static_pages#blog'
      get '/developers' => 'static_pages#developers'
      get '/jobs'  => 'static_pages#jobs'
      get '/privacy' => 'static_pages#privacy'
      get '/terms'   => 'static_pages#terms'
      get '/contact' => 'static_pages#contact'
      get '/help'	 => 'static_pages#help'
    end

      
      resources :events
      resources :reasons
      resources :moods 
      resources :sub_moods

    match '/moods_for_selection' => 'home#moods_for_selection'
    match '/edit_profile' => 'home#edit_profile'
    match '/profile' => 'home#profile'
    match '/home/update_state_select/:id' => 'home#update_state_select'
    match '/home/update_city_select/:id' => 'home#update_city_select'
    match '/enter_sub_mood' => 'home#enter_sub_mood'
    match '/home/city_for_graph/:id' => 'home#city_for_graph' 
      

    
    
    
    devise_for :users,
      :controllers => { 
	      :sessions           => 'devise/sessions', 
	      :registrations      => 'devise/registrations', 
	      :confirmations      => 'devise/confirmations', 
        :passwords          => 'devise/passwords',
        :omniauth_callbacks => 'users/omniauth_callbacks'
      }, :path => '', :path_names => {
                        :sign_in => 'users/sign_in', 
                        :sign_out => 'users/sign_out', 
                        :sign_up => 'users/sign_up'
                      }
    resources :users
    
    
    
    root :to => "home#index"
  end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
  <%= link_to "MoodyOn.com", root_path, :class => 'brand' %>
  <ul class="nav" style="float: right;">
    <% if user_signed_in? %>
      <li>
	<%= link_to "Home", root_path %>
      </li>
      <li class="dropdown">
	<a data-toggle="dropdown" class="dropdown-toggle" href="#"><%= current_user.name %><b class="caret"></b></a>
	<ul class="dropdown-menu">
	  <li>
	    <%= link_to "Your Profile", current_user %>
	  </li>
	  <li>
	    <%= link_to "Add Friends", "#"%>
	  </li>
	  <li>
	    <%= link_to "Settings", {:action => "edit_profile", :controller => "home"} %>
	  </li>
	  <li>
	    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete', :id => "sign_out" %>        
	  </li>
	</ul>
      </li>
    <% else %>
      <li>
	<%= link_to 'Login', new_user_session_path %>  
      </li>
      <li>
	<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :id => "sign_in" %>
      </li>  
    <% end %>
    <% if user_signed_in? %>
      <li>
	<%= link_to 'Admin', users_path  if current_user.has_role? :admin %>
      </li>
    <% else %>
      <li>
	<%= link_to 'Sign up', new_user_registration_path %>
      </li>
    <% end %>
  </ul>

  <div id="fb-root"></div>

  <script>
    window.fbAsyncInit = function() {
      FB.init({
	appId      : '215267491940472',
	status     : true,
	channelURL : 'http://localhost:3000/channel.html',
	cookie     : true,
	oauth      : true,
	xfbml      : true
      });
    };
  
    $('#sign_in').click(function(e) {
      e.preventDefault();
      FB.login(function(response) {
	if (response.authResponse) {
	  console.log('Welcome!  Fetching your information.... ');
	  window.location = '/auth/facebook/callback';
	  FB.api('/me', function(response) {
	    console.log('Good to see you, ' + response.name + response.email +'.');
	  });
	} else {
	    console.log('User cancelled login or did not fully authorize.');
	}
      }, {scope: 'email, user_about_me, user_birthday, user_hometown, user_location, user_relationships, user_status, user_work_history, user_education_history, user_likes, read_stream, offline_access'});
    });
    
    $('#sign_out').click(function(){
      FB.api('/me', function(response) {
	console.log('Good bye, ' + response.name + '.');
	FB.logout(function(response) {
	  console.log('Logged out.');
	});
      });
    });
  
    (function() {
      var e = document.createElement('script'); e.async = true;
      e.src = document.location.protocol 
      + '//connect.facebook.net/en_US/all.js';
      document.getElementById('fb-root').appendChild(e);
    }());
  </script>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MoodyOn.com" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "MoodyOn.com" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
      	  <footer class="navbar navbar-fixed-bottom">
      	    <nav class="navbar-inner">
      	      <div class="container">
                	<%= link_to "About Us", about_path %> | 
                	<%= link_to "Blog", blog_path %> | 
                	<%= link_to "Developers", developers_path %> | 
                	<%= link_to "Jobs", jobs_path %> | 
                	<%= link_to "Privacy", privacy_path %> | 
                	<%= link_to "Terms", terms_path %> | 
                	<%= link_to "Contact Us", contact_path %> | 
                	<%= link_to "Help", help_path %> | 
                  <div id="copyright" style="float:right;">
                    moodyon.com &copy; 2012 [BluePlanet Infosolutions Pvt. Ltd.]
                  </div>
      	      </div>
            </nav>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>